import ReactMarkdown from 'react-markdown';

/**
 * Stage3Display: renders the Lead Counsel synthesis memo in letterhead style.
 *
 * Props:
 *   stage3: { model: string, content: string | null, error: string | null }
 */
function Stage3Display({ stage3 }) {
  if (!stage3) {
    return <div className="text-gray-500 py-8">No final strategy yet.</div>;
  }

  // Lead Counsel failed but Stage 1 + Stage 2 still ran.
  if (stage3.error && !stage3.content) {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="bg-red-50 border-l-4 border-red-600 p-5 rounded">
          <div className="font-display text-xl text-red-900 mb-2">
            Lead Counsel synthesis failed
          </div>
          <p className="text-sm text-red-800 mb-2">
            The Lead Counsel model was unable to synthesize a final memorandum.
            Stage 1 and Stage 2 results remain available in their respective tabs.
          </p>
          <p className="text-xs font-mono text-red-700 mt-3 bg-red-100 p-2 rounded">
            {stage3.error}
          </p>
        </div>
      </div>
    );
  }

  if (!stage3.content) {
    return <div className="text-gray-500 py-8">No final strategy yet.</div>;
  }

  return (
    <div className="max-w-4xl mx-auto">
      {/* Disclaimer */}
      <div className="bg-red-50 border-l-4 border-red-600 px-4 py-3 mb-4 rounded-sm">
        <p className="text-xs text-red-900 leading-relaxed">
          <strong className="font-semibold">DISCLAIMER:</strong>{' '}
          This AI-generated analysis is not legal advice. Review by a licensed
          attorney is required before any implementation. Attorney-client
          privilege does not apply to interactions with this system.
        </p>
      </div>

      {/* Letterhead */}
      <div className="bg-legal-navy text-legal-cream">
        <div className="px-10 py-8">
          <div className="flex items-start justify-between">
            <div>
              <div className="text-[10px] font-mono uppercase tracking-[0.3em] text-legal-gold mb-2">
                In the matter of · Final memorandum · Stage III
              </div>
              <h2 className="font-display text-4xl leading-tight">
                Lead Counsel
                <span className="block italic text-3xl opacity-90">
                  Strategy Memorandum
                </span>
              </h2>
            </div>
            <div className="text-right flex-shrink-0 ml-6">
              <div className="text-5xl">⚖</div>
              <div className="text-[9px] font-mono mt-2 text-legal-gold uppercase tracking-wider">
                Synthesized by
              </div>
              <div className="text-[10px] font-mono mt-1 opacity-80">
                {stage3.model}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Gold rule bar */}
      <div className="h-[6px] letterhead-rule" />

      {/* Memo body */}
      <div className="bg-white shadow-lg">
        <div className="px-10 py-10 legal-prose">
          <ReactMarkdown>{stage3.content}</ReactMarkdown>
        </div>

        {/* Footer rule + metadata */}
        <div className="border-t border-gray-200 px-10 py-5 bg-legal-parchment">
          <div className="flex items-center justify-between text-xs text-gray-600">
            <span className="font-mono">
              ⚖ LLM-COUNSEL · Multi-Model Legal Strategy Deliberation
            </span>
            <span className="font-mono">
              {new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
            </span>
          </div>
          <p className="text-[11px] text-gray-500 italic mt-3 leading-relaxed">
            This memorandum is generated by AI for informational purposes only.
            All legal strategies require review by a licensed attorney before
            implementation.
          </p>
        </div>
      </div>

      {/* Action buttons */}
      <div className="mt-6 flex gap-3 justify-center">
        <button
          onClick={() => {
            navigator.clipboard.writeText(stage3.content);
          }}
          className="px-5 py-2 bg-white border border-gray-300 rounded text-sm hover:bg-legal-parchment transition-colors"
        >
          Copy to Clipboard
        </button>
        <button
          onClick={() => {
            const blob = new Blob([stage3.content], { type: 'text/markdown' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'legal-strategy-memo.md';
            a.click();
            URL.revokeObjectURL(url);
          }}
          className="px-5 py-2 bg-legal-navy text-white rounded text-sm hover:bg-blue-900 transition-colors"
        >
          Download as Markdown
        </button>
      </div>
    </div>
  );
}

export default Stage3Display;
